version: '3.4'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jdma
    ports:
      - '5433:5432'

networks:
  jdma:
