version: "3.4"

services:
  elasticsearch:
    build: docker/elasticsearch
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - jdma_es_data:/usr/share/elasticsearch/data
      - jdma_es_certs:/usr/share/elasticsearch/config/certs
    networks:
      - elastic
    environment:
      - ELASTIC_PASSWORD=${ES_ADDON_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g

  kibana:
    build: docker/kibana
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - jdma_kibana_data:/usr/share/kibana/data
      - jdma_es_certs:/usr/share/kibana/config/certs
    networks:
      - elastic
    environment:
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jdma
    ports:
      - "5433:5432"

networks:
  elastic:

volumes:
  jdma_kibana_data:
  jdma_es_data:
  jdma_es_certs:
