import './bo/home.cy.js';
import './bo/admin.cy.js';
import './bo/register.cy.js';
import './form/review.cy.js';
import './bo/reviewCheck.cy.js';
import './bo/account.cy.js';
import './bo/users.cy.js';
import './bo/logs.cy.js';
import './bo/product.cy.js';
