name: CI

on:
  push:
    branches: ['main', 'staging']
  pull_request:
    branches: ['main', 'staging']

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-webapp-backoffice:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: webapp-backoffice/yarn.lock

      - name: Build webapp-backoffice
        run: |
          cd webapp-backoffice
          yarn install --frozen-lockfile
          yarn build

  build-webapp-form:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: webapp-form/yarn.lock

      - name: Build webapp-form
        run: |
          cd webapp-form
          yarn install --frozen-lockfile
          yarn build
