name: Run Cypress Tests

on:
  pull_request:
    branches:
      - feat/clevercloud
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          docker-compose up -d

      # 4. Attendre que les services soient prêts
      - name: Wait for services to be ready
        run: |
          echo "Waiting for webapp-backoffice to be ready..."
          until curl -s http://localhost:3000 > /dev/null; do echo "Waiting for webapp-backoffice..."; sleep 5; done

          echo "Waiting for webapp-form to be ready..."
          until curl -s http://localhost:3001 > /dev/null; do echo "Waiting for webapp-form..."; sleep 5; done

          echo "Waiting for MailHog to be ready..."
          until curl -s http://localhost:8025 > /dev/null; do echo "Waiting for MailHog..."; sleep 5; done

      # 5. Exécuter les tests Cypress pour `webapp-backoffice`
      - name: Run Cypress tests for webapp-backoffice
        working-directory: ./webapp-backoffice
        run: npx cypress run --spec "cypress/e2e/jdma/launcher.cy.js" --headed --browser chrome

      # 6. Vérifier si MailHog reçoit les emails
      - name: Check MailHog for received emails
        run: curl http://localhost:8025/api/v2/messages

      # 7. Arrêter Docker Compose
      - name: Stop Docker Compose
        run: docker-compose down
