name: Run Cypress Tests

on:
  pull_request:
    branches:
      - feat/clevercloud
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: jdma
        ports:
          - 5433:5432
      mailhog:
        image: mailhog/mailhog
        ports:
          - 8025:8025
          - 1025:1025

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      # Étape de vérification du fichier yarn.lock pour `webapp-backoffice`
      - name: Verify yarn.lock for webapp-backoffice
        run: |
          cd webapp-backoffice
          if [ ! -f yarn.lock ]; then
            echo "No yarn.lock file found for webapp-backoffice, generating it..."
            yarn install
          fi

      # Étape de vérification du fichier yarn.lock pour `webapp-form`
      - name: Verify yarn.lock for webapp-form
        run: |
          cd webapp-form
          if [ ! -f yarn.lock ]; then
            echo "No yarn.lock file found for webapp-form, generating it..."
            yarn install
          fi

      # Installation des dépendances et construction de `webapp-backoffice`
      - name: Install dependencies and build webapp-backoffice
        run: |
          cd webapp-backoffice
          yarn install
          yarn build
          nohup yarn start &

      # Installation des dépendances et construction de `webapp-form`
      - name: Install dependencies and build webapp-form
        run: |
          cd webapp-form
          yarn install
          yarn build
          nohup yarn startB &

      # Attendre que les services soient prêts
      - name: Wait for services to be ready
        run: |
          echo "Waiting for webapp-backoffice to be ready..."
          until curl -s http://localhost:3000 > /dev/null; do echo "Waiting for webapp-backoffice..."; sleep 5; done

          echo "Waiting for webapp-form to be ready..."
          until curl -s http://localhost:3001 > /dev/null; do echo "Waiting for webapp-form..."; sleep 5; done

      # Exécuter les tests Cypress pour `webapp-backoffice`
      - name: Run Cypress tests for webapp-backoffice
        working-directory: ./webapp-backoffice
        run: npx cypress run

      # Exécuter les tests Cypress pour `webapp-form`
      - name: Run Cypress tests for webapp-form
        working-directory: ./webapp-form
        run: npx cypress run

      # Arrêter les applications démarrées
      - name: Stop applications
        run: |
          pkill -f "yarn start" || true
          pkill -f "yarn startB" || true
